### ISSUE TITLE
Merging two different profiles

### ISSUE THREAD

**Issue by AlbertoFabbri93** [Nanostring-Biostats/CosMx-Cell-Profiles#6]
Is it possible or recommended to merge two different reference profiles? I am working on brain metastases data and would like to merge the 1000-gene IO profile with the 6K brain profile.

I noticed that the 6K panel is missing 62 genes that are present in the IO profile. When creating a merged profile, should I retain these genes by assigning them arbitrary values (and if so, what values should I use?), or would it be better to exclude them entirely?

**Comment by mgrout81** [comment]
Hello, thank you for your patience. To combine matrices, please see our tutorial on our Scratch Space website here: 
https://nanostring-biostats.github.io/CosMx-Analysis-Scratch-Space/posts/hybrid-reference-profiles/. The example shown is combing two scRNAseq-derived matrices, but since you're still combining two matrices derived from one platform type (CosMx SMI), this should also work.
